name: Neutrino Monorepo Build/Lint/Test

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [ '12', '14', '16' ]

    name: Node ${{ matrix.node}} on ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install modules
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run validate:eslintrc
        run: yarn validate:eslintrc

      - name: Run lint
        run: yarn lint

      - name: Run prettier:check
        run: yarn prettier:check

      - name: Run unit tests
        run: yarn test

      - name: Create test project with yarn
        run: scripts/test-create-project-ci.sh
        env:
          CREATE_PROJECT_YARN: 'true'

      - name: Create test project with npm
        run: scripts/test-create-project-ci.sh
        env:
          CREATE_PROJECT_YARN: 'false'
