name: Neutrino Monorepo Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install modules
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run validate:eslintrc
        run: yarn validate:eslintrc

      - name: Run lint
        run: yarn lint

      - name: Run prettier:check
        run: yarn prettier:check
