name: Neutrino Monorepo Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['12', '14', '16']

    name: Node ${{ matrix.node }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install modules
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run unit tests
        run: yarn test

      - name: Create test project with yarn
        run: scripts/test-create-project-ci.sh
        env:
          CREATE_PROJECT_YARN: 'true'

      - name: Create test project with npm
        run: scripts/test-create-project-ci.sh
        env:
          CREATE_PROJECT_YARN: 'false'
